export const orderStatus = ["PENDING_REVIEW", "ACCEPTED", "REJECTED", "AWAITING_PAYMENT", "PAID", "IN_PRODUCTION", "READY_FOR_DELIVERY", "SHIPPED", "DELIVERED", "COMPLETED", "CANCELLED"]

export const paymentStatus = ["UNPAID", "PARTIALLY_PAID", "PAID", "REFUNDED", "FAILED", "PENDING", "SUCCESS"]

export const dressCategory = ["FEMALE_NATIVE", "MALE_NATIVE", "CORPORATE_MALE", "CORPORATE_FEMALE", "CASUAL", "STREET_WEAR"]